In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
df=pd.read_csv('Database/Sales_transactions_2022_2025.csv')
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
18041,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
18042,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
18043,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
18044,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

| Name | Description |
|------|-------------|
| Transaction_ID | Unique ID of one sales line |
| Order_ID | Order/basket ID; one order can have several rows |
| Customer_ID | Customer identifier (use this instead of the name) |
| Customer_Name | Customer full name; not a reliable key |
| Customer_Age | Customer age in years |
| Customer_Gender | Female / Male / Non-binary |
| Customer_Segment | Consumer, Small Business, Corporate, Premium, New Customer, Returning Customer |
| Order_Date | Date the order was placed |
| Order_Time | Time of day the order was placed |
| Sales_Channel | Online, Retail Store, B2B Portal, Phone Order |
| Store_ID | Store code |
| Store_Name | Store name (1-to-1 with Store_ID) |
| Country | Country of the store |
| Region | State / province / region |
| City | City of the store |
| Product_ID | Product code (28 products) |
| Product_Name | Product name (1-to-1 with Product_ID) |
| Product_Category | Electronics, Office Supplies, Furniture, Appliances |
| Product_Subcategory | Detailed group inside the category |
| Quantity | Units sold on the line |
| Unit_Price | List price per unit before discount |
| Discount_Percentage | Discount applied, in % |
| Sales_Amount | Revenue = Quantity × Unit_Price × (1 − Discount/100) |
| Cost_Amount | Total cost of goods for the line |
| Profit | Sales_Amount − Cost_Amount (negative = loss) |
| Payment_Method | Credit Card, Debit Card, PayPal, Bank Transfer, Apple Pay, Cash |
| Order_Status | Completed, Shipped, Processing, Returned, Cancelled |
| Shipping_Method | Standard, Express, Next Day, Pickup |
| Delivery_Days | Days from order to delivery (0 = same day / pickup) |
| Return_Flag | Yes / No: was the item returned |
| Return_Reason | Why it was returned; empty when Return_Flag = No |
| Sales_Representative | Sales rep who handled the order |
| Promotion_Code | Promo code used; empty = no promotion |
| Customer_Rating | Satisfaction score, 1 (worst) to 5 (best) |
| Inventory_Level | Stock units on hand at the time of sale |
| Order_Year | Year taken from Order_Date (2022–2025) |

## Data Exploration

In [4]:
df.columns

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Age', 'Customer_Gender', 'Customer_Segment', 'Order_Date',
       'Order_Time', 'Sales_Channel', 'Store_ID', 'Store_Name', 'Country',
       'Region', 'City', 'Product_ID', 'Product_Name', 'Product_Category',
       'Product_Subcategory', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Method',
       'Order_Status', 'Shipping_Method', 'Delivery_Days', 'Return_Flag',
       'Return_Reason', 'Sales_Representative', 'Promotion_Code',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='object')

# Check Data Types

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18045 entries, 0 to 18044
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction_ID        18045 non-null  object
 1   Order_ID              18045 non-null  object
 2   Customer_ID           18045 non-null  object
 3   Customer_Name         17937 non-null  object
 4   Customer_Age          17827 non-null  float64
 5   Customer_Gender       17883 non-null  object
 6   Customer_Segment      18045 non-null  object
 7   Order_Date            18045 non-null  object
 8   Order_Time            18045 non-null  object
 9   Sales_Channel         18045 non-null  object
 10  Store_ID              18045 non-null  object
 11  Store_Name            18045 non-null  object
 12  Country               18045 non-null  object
 13  Region                18045 non-null  object
 14  City                  18045 non-null  object
 15  Product_ID            18045 non-null  object
 16  Product_Name          17901 non-null  object
 17  Product_Category      18045 non-null  object
 18  Product_Subcategory   18045 non-null  object
 19  Quantity              18045 non-null  int64
 20  Unit_Price            18045 non-null  float64
 21  Discount_Percentage   18045 non-null  float64
 22  Sales_Amount          18045 non-null  float64
 23  Cost_Amount           18045 non-null  float64
 24  Profit                18045 non-null  float64
 25  Payment_Method        17898 non-null  object
 26  Order_Status          18045 non-null  object
 27  Shipping_Method       18045 non-null  object
 28  Delivery_Days         17883 non-null  float64
 29  Return_Flag           18045 non-null  object
 30  Return_Reason         1877 non-null   object
 31  Sales_Representative  18045 non-null  object
 32  Promotion_Code        8308 non-null   object
 33  Customer_Rating       14610 non-null  float64
 34  Inventory_Level       17847 non-null  float64
 35  Order_Year            18045 non-null  int64
dtypes: float64(9), int64(2), object(25)
memory usage: 5.0+ MB

# 2- Check duplicates

In [6]:
df.duplicated().sum()

np.int64(45)

In [7]:
df[df.duplicated()]

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
602,T02009714,O0109714,C04340,Mia Anderson,52.0,Female,Consumer,2025-11-13,11:39:31,Phone Order,...,Completed,Next Day,4.0,No,NaN,Ella Lewis,SAVE10,5.0,93.0,2025
3868,T02003428,O0103428,C01135,Leo Green,NaN,Female,Corporate,2022-10-09,17:17:30,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Amelia Jackson,NaN,5.0,74.0,2022
4133,T02004930,O0104930,C00123,Grace Nelson,44.0,Female,Corporate,2023-04-17,10:07:47,Phone Order,...,Completed,Standard,2.0,No,NaN,Liam Davis,BACK2WORK,5.0,58.0,2023
4471,T02000103,O0100051,C02559,James Williams,34.0,Male,Returning Customer,2022-04-05,15:41:57,B2B Portal,...,Completed,Standard,7.0,No,NaN,Amelia Jackson,SAVE10,5.0,79.0,2022
6568,T02002644,O0102644,C01805,David Moore,43.0,Male,Consumer,2022-06-09,15:52:08,B2B Portal,...,Completed,Pickup,0.0,No,NaN,Olivia Martin,NaN,4.0,106.0,2022
7041,T02010013,O0105006,C05246,Ella Hall,34.0,Male,Consumer,2024-05-08,10:27:59,Retail Store,...,Completed,Pickup,0.0,No,NaN,Ella Lewis,NaN,4.0,86.0,2024
7069,T02015002,O0115002,C04984,Benjamin Thompson,31.0,Male,Corporate,2023-06-06,18:26:27,Retail Store,...,Returned,Pickup,0.0,Yes,Other,Lucas Moore,NaN,5.0,53.0,2023
7504,T02008527,O0108527,C03964,Jack Miller,42.0,Male,Returning Customer,2025-11-28,16:35:25,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Lucas Moore,NaN,5.0,84.0,2025
7675,T02008170,O0104085,C00246,Ava Taylor,40.0,Male,Returning Customer,2024-11-28,11:01:16,B2B Portal,...,Cancelled,Pickup,0.0,No,NaN,Amelia Jackson,SPRING15,4.0,42.0,2024
7914,T02005299,O0105299,C05437,Noah Thompson,18.0,FEMALE,Corporate,2024-04-21,09:53:02,Retail Store,...,Shipped,Pickup,0.0,No,NaN,James Anderson,NaN,4.0,123.0,2024
7923,T02004986,O0104986,C02621,Benjamin Walker,62.0,Male,New Customer,2022-03-17,13:45:50,Online,...,Completed,Express,1.0,No,NaN,Liam Davis,BLACKFRIDAY25,4.0,46.0,2022
8825,T02007889,O0107889,C02127,William Taylor,18.0,Female,Premium,2024-05-03,18:47:59,Online,...,Processing,Standard,3.0,No,NaN,Ella Lewis,NaN,3.0,95.0,2024
9039,T02004225,O0104225,C00072,Jack Smith,47.0,Male,Returning Customer,2024-06-27,17:28:51,Online,...,Shipped,Standard,4.0,No,NaN,Michael Clark,NaN,4.0,58.0,2024
9128,T02008291,O0108291,C02549,Ava Walker,39.0,Male,Small Business,2023-01-03,18:36:00,Online,...,Returned,Standard,7.0,Yes,Wrong Item,James Anderson,NaN,2.0,77.0,2023
9590,T02017285,O0117285,C03739,Grace Hall,38.0,Female,Consumer,2024-05-28,11:47:50,Retail Store,...,Completed,Standard,4.0,No,NaN,Henry White,NaN,4.0,73.0,2024
9835,T02000746,O0100373,C04097,Grace Thompson,39.0,Female,Small Business,2025-09-22,13:30:26,Retail Store,...,Completed,Pickup,0.0,No,NaN,Ella Lewis,NaN,5.0,84.0,2025
10113,T02003264,O0103264,C00168,Alexander Wright,48.0,Female,Consumer,2025-12-09,14:54:24,Online,...,Completed,Standard,6.0,No,NaN,Michael Clark,MOM15,4.0,54.0,2025
10391,T02009907,O0109907,C03188,William Smith,18.0,Male,Corporate,2023-11-13,16:13:03,B2B Portal,...,Completed,Pickup,0.0,No,NaN,Michael Clark,NaN,NaN,53.0,2023
10705,T02003151,O0101575,C03525,Emma King,51.0,Female,New Customer,2022-10-06,17:20:13,Online,...,Completed,Next Day,1.0,No,NaN,Henry White,NaN,NaN,95.0,2022
10767,T02004194,O0102097,C05378,Olivia Williams,56.0,Female,Corporate,2022-05-17,15:42:53,Online,...,Processing,Next Day,1.0,No,NaN,Mia Taylor,NaN,5.0,100.0,2022
10924,T02005256,O0105256,C00930,Amelia Allen,57.0,Male,Corporate,2023-11-26,16:01:04,Phone Order,...,Cancelled,Standard,6.0,No,NaN,Noah Wilson,NaN,3.0,107.0,2023
10972,T02001529,O0101529,C01893,David Thomas,41.0,Male,Consumer,2022-12-20,11:59:46,B2B Portal,...,Completed,Standard,3.0,No,NaN,Michael Clark,NaN,3.0,86.0,2022
11014,T02003561,O0103561,C03829,Freya Brown,58.0,Female,Consumer,2025-12-12,16:35:32,Online,...,Completed,Express,1.0,No,NaN,Ella Lewis,NaN,5.0,63.0,2025
11498,T02015436,O0115436,C00771,Amelia King,NaN,Male,Premium,2023-05-30,18:21:47,Online,...,Completed,Pickup,0.0,No,NaN,Liam Davis,BACK2WORK,5.0,54.0,2023
11514,T02003202,O0101601,C01986,Amelia Walker,47.0,Male,Returning Customer,2023-02-23,16:04:52,Online,...,Returned,Standard,3.0,Yes,Wrong Item,Charlotte Thomas,SPRING15,5.0,68.0,2023
11587,T02007846,O0107846,C03255,David Miller,48.0,Male,Corporate,2023-11-17,11:00:35,Retail Store,...,Completed,Pickup,0.0,No,NaN,Henry White,NaN,3.0,85.0,2023
12487,T02006187,O0103093,C03389,Amelia Allen,36.0,Female,Small Business,2022-03-16,16:31:48,Retail Store,...,Returned,Standard,3.0,Yes,Wrong Item,Emma Carter,HALLOWEEN15,1.0,98.0,2022
12490,T02000375,O0100375,C04190,Theo Clark,18.0,Female,Returning Customer,2025-09-29,14:45:26,Online,...,Completed,Standard,7.0,No,NaN,Grace Harris,NaN,2.0,67.0,2025
12499,T02012758,O0112758,C04888,Evelyn Moore,21.0,Female,Small Business,2024-08-26,18:13:27,Online,...,Shipped,Standard,3.0,No,NaN,Noah Wilson,NaN,NaN,73.0,2024
13176,T02002892,O0102892,C04336,Grace Davis,18.0,Female,Premium,2025-11-04,10:38:11,Retail Store,...,Completed,Pickup,0.0,No,NaN,Noah Wilson,MOM15,3.0,76.0,2025
13325,T02016423,O0116423,C05597,Max Thomas,33.0,Female,Small Business,2023-05-04,11:55:11,Phone Order,...,Cancelled,Pickup,0.0,No,NaN,Daniel Miller,NaN,4.0,66.0,2023
13441,T02015596,O0115596,C05463,Samuel Adams,50.0,Female,Corporate,2024-04-27,15:42:38,Online,...,Completed,Standard,1.0,No,NaN,Liam Davis,BLACKFRIDAY25,5.0,85.0,2024
13940,T02012050,O0112050,C05094,Samuel Johnson,38.0,Male,Corporate,2024-12-13,13:55:03,Online,...,Shipped,Standard,8.0,No,NaN,James Anderson,NaN,3.0,104.0,2024
14210,T02002832,O0102832,C05359,Max Thomas,37.0,Female,Corporate,2023-01-13,12:18:23,B2B Portal,...,Completed,Express,1.0,No,NaN,Amelia Jackson,VALENTINE20,5.0,34.0,2023
14400,T02004731,O0104731,C05226,Lucas Williams,32.0,Female,Consumer,2024-12-23,18:14:24,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Amelia Jackson,NaN,5.0,55.0,2024
15022,T02005072,O0102536,C03265,Henry White,31.0,Female,Consumer,2025-12-18,13:27:41,Retail Store,...,Completed,Pickup,0.0,No,NaN,Charlotte Thomas,HOLIDAY20,3.0,59.0,2025
15259,T02005853,O0105853,C03490,David Thomas,47.0,Female,Consumer,2022-10-18,13:42:31,Retail Store,...,Completed,Pickup,0.0,No,NaN,Olivia Martin,MOM15,NaN,111.0,2022
15799,T02000689,O0100344,C01832,Olivia Walker,32.0,Male,Small Business,2022-04-30,17:47:27,Retail Store,...,Completed,Standard,5.0,No,NaN,Grace Harris,NaN,3.0,60.0,2022
15977,T02006502,O0106502,C05481,Lucas Green,49.0,Male,Small Business,2024-02-17,19:11:35,Online,...,Completed,Standard,5.0,No,NaN,Henry White,BACK2WORK,5.0,44.0,2024
16063,T02017513,O0117513,C03757,Ella Nelson,29.0,Female,Corporate,2024-09-16,16:20:06,B2B Portal,...,Completed,Next Day,2.0,No,NaN,David Walker,NaN,NaN,34.0,2024
16127,T02005710,O0105710,C02007,Hannah King,50.0,Male,Small Business,2025-08-10,14:13:20,B2B Portal,...,Processing,Next Day,1.0,No,NaN,Daniel Miller,HOLIDAY20,5.0,71.0,2025
16787,T02013564,O0113564,C01107,Arthur White,27.0,Female,Corporate,2025-08-09,19:56:18,Online,...,Completed,Standard,6.0,No,NaN,Mia Taylor,VALENTINE20,4.0,54.0,2025
17469,T02017831,O0117831,C02820,Thomas Nelson,63.0,Non-binary,Corporate,2024-09-30,17:35:33,Retail Store,...,Cancelled,Pickup,0.0,No,NaN,Mia Taylor,CORP5,5.0,53.0,2024
17624,T02000929,O0100929,C02671,Thomas Baker,31.0,Non-binary,Consumer,2024-11-16,17:28:09,Retail Store,...,Completed,Pickup,0.0,No,NaN,Michael Clark,MOM15,5.0,101.0,2024
17985,T02000019,O0100009,C02496,Chloe Williams,26.0,Male,Consumer,2024-07-15,14:32:58,B2B Portal,...,Cancelled,Standard,4.0,No,NaN,Michael Clark,HOLIDAY20,4.0,120.0,2024

# Drop duplicates

In [8]:
df = df.drop_duplicates()
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
18041,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
18042,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
18043,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
18044,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

In [9]:
df= df.reset_index(drop=True)
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
17996,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
17997,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
17998,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
17999,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

## 3 - Check summary for numerical values

In [10]:
df.describe().round(1)

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17784.0,18000.0,18000.0,18000.0,18000.0,18000.0,18000.0,17838.0,14570.0,17802.0,18000.0
mean,38.9,2.1,232.8,6.3,457.4,366.1,91.4,2.3,4.0,70.2,2023.6
std,10.7,1.8,294.2,6.9,857.1,706.3,167.9,2.3,1.0,22.0,1.1
min,4.0,-3.0,21.4,0.0,16.7,12.2,-299.3,0.0,1.0,0.0,2022.0
25%,32.0,1.0,53.0,0.0,78.5,56.1,19.5,0.0,4.0,55.0,2023.0
50%,39.0,2.0,99.8,5.0,168.8,122.3,40.2,1.0,4.0,70.0,2024.0
75%,46.0,3.0,285.8,10.0,472.7,376.1,93.3,4.0,5.0,85.0,2025.0
max,112.0,11.0,1425.1,110.0,14303.1,10791.0,3512.1,10.0,5.0,157.0,2025.0

## 4 - Check summary for categorical values

In [11]:
df.describe(include= ['object'])

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,Store_ID,...,Product_Name,Product_Category,Product_Subcategory,Payment_Method,Order_Status,Shipping_Method,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code
count,18000,18000,18000,17892,17838,18000,18000,18000,18000,18000,...,17856,18000,18000,17856,18000,18000,18000,1873,18000,8288
unique,18000,14541,4882,1179,6,6,1461,15201,4,12,...,28,7,17,10,8,4,2,6,16,10
top,T02016694,O0107988,C02559,Amelia King,Female,Consumer,2024-12-25,12:29:48,Online,NYC-01,...,Copy Paper Box,Electronics,Accessories,Credit Card,Completed,Standard,No,Late Delivery,Sophia Brown,HOLIDAY20
freq,1,3,20,57,8720,8027,33,5,8195,2170,...,975,8121,3236,6725,11436,7735,16127,331,1166,1396

In [12]:
df['Customer_Gender'].unique()

array(['Male', 'Female', 'Non-binary', 'male', 'FEMALE', nan,
       'Non Binary'], dtype=object)

In [13]:
df.head()

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022

## 4-Check Missing Values

In [14]:
df.isna().sum()

Transaction_ID              0
Order_ID                    0
Customer_ID                 0
Customer_Name             108
Customer_Age              216
Customer_Gender           162
Customer_Segment            0
Order_Date                  0
Order_Time                  0
Sales_Channel               0
Store_ID                    0
Store_Name                  0
Country                     0
Region                      0
City                        0
Product_ID                  0
Product_Name              144
Product_Category            0
Product_Subcategory         0
Quantity                    0
Unit_Price                  0
Discount_Percentage         0
Sales_Amount                0
Cost_Amount                 0
Profit                      0
Payment_Method            144
Order_Status                0
Shipping_Method             0
Delivery_Days             162
Return_Flag                 0
Return_Reason           16127
Sales_Representative        0
Promotion_Code           9712
Customer_Rating          3430
Inventory_Level           198
Order_Year                  0
dtype: int64

In [15]:
df.isna().mean().round(2)*100

Transaction_ID           0.0
Order_ID                 0.0
Customer_ID              0.0
Customer_Name            1.0
Customer_Age             1.0
Customer_Gender          1.0
Customer_Segment         0.0
Order_Date               0.0
Order_Time               0.0
Sales_Channel            0.0
Store_ID                 0.0
Store_Name               0.0
Country                  0.0
Region                   0.0
City                     0.0
Product_ID               0.0
Product_Name             1.0
Product_Category         0.0
Product_Subcategory      0.0
Quantity                 0.0
Unit_Price               0.0
Discount_Percentage      0.0
Sales_Amount             0.0
Cost_Amount              0.0
Profit                   0.0
Payment_Method           1.0
Order_Status             0.0
Shipping_Method          0.0
Delivery_Days            1.0
Return_Flag              0.0
Return_Reason           90.0
Sales_Representative     0.0
Promotion_Code          54.0
Customer_Rating         19.0
Inventory_Level          1.0
Order_Year               0.0
dtype: float64

In [16]:
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
17996,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
17997,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
17998,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
17999,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

## 5- Cleaning data

### Droping unnecessary Columns

In [17]:
df=df.drop (['Transaction_ID','Order_ID','Customer_ID','Store_ID','Product_ID','Return_Reason','Promotion_Code'],axis=1 )

In [18]:
pd.set_option('display.max_columns',None)

In [19]:
df.describe().round(2)

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17784.00,18000.00,18000.00,18000.00,18000.00,18000.00,18000.00,17838.00,14570.00,17802.00,18000.00
mean,38.92,2.13,232.78,6.25,457.45,366.13,91.41,2.26,3.99,70.25,2023.57
std,10.72,1.78,294.25,6.88,857.10,706.34,167.86,2.32,1.01,22.04,1.12
min,4.00,-3.00,21.39,0.00,16.68,12.17,-299.31,0.00,1.00,0.00,2022.00
25%,32.00,1.00,52.96,0.00,78.53,56.10,19.49,0.00,4.00,55.00,2023.00
50%,39.00,2.00,99.84,5.00,168.84,122.32,40.19,1.00,4.00,70.00,2024.00
75%,46.00,3.00,285.78,10.00,472.74,376.14,93.30,4.00,5.00,85.00,2025.00
max,112.00,11.00,1425.09,110.00,14303.07,10791.00,3512.08,10.00,5.00,157.00,2025.00

In [20]:
df.describe(include='object')

,Customer_Name,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Payment_Method,Order_Status,Shipping_Method,Return_Flag,Sales_Representative
count,17892,17838,18000,18000,18000,18000,18000,18000,18000,18000,17856,18000,18000,17856,18000,18000,18000,18000
unique,1179,6,6,1461,15201,4,12,6,14,15,28,7,17,10,8,4,2,16
top,Amelia King,Female,Consumer,2024-12-25,12:29:48,Online,New York Central,United States,England,New York,Copy Paper Box,Electronics,Accessories,Credit Card,Completed,Standard,No,Sophia Brown
freq,57,8720,8027,33,5,8195,2170,7526,2974,2156,975,8121,3236,6725,11436,7735,16127,1166

In [21]:
df.isna().mean().round(2)*100

Customer_Name            1.0
Customer_Age             1.0
Customer_Gender          1.0
Customer_Segment         0.0
Order_Date               0.0
Order_Time               0.0
Sales_Channel            0.0
Store_Name               0.0
Country                  0.0
Region                   0.0
City                     0.0
Product_Name             1.0
Product_Category         0.0
Product_Subcategory      0.0
Quantity                 0.0
Unit_Price               0.0
Discount_Percentage      0.0
Sales_Amount             0.0
Cost_Amount              0.0
Profit                   0.0
Payment_Method           1.0
Order_Status             0.0
Shipping_Method          0.0
Delivery_Days            1.0
Return_Flag              0.0
Sales_Representative     0.0
Customer_Rating         19.0
Inventory_Level          1.0
Order_Year               0.0
dtype: float64

#### Drop NA in Rows

In [26]:
df=df.dropna(subset= ['Customer_Name', 'Customer_Age','Customer_Gender','Product_Name','Payment_Method','Delivery_Days','Inventory_Level'], ignore_index= True)
df

,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
0,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,Los Angeles Downtown,United States,West,LOS ANGELES,Webcam HD,Electronics,Cameras,2,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81.0,2022
1,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123.0,2024
2,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93.0,2024
3,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11,115.34,15.0,1078.46,897.91,180.55,paypal,Completed,Next Day,2.0,No,Grace Harris,NaN,59.0,2025
4,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16886,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,Sydney CBD,Australia,New South Wales,Sydney,Portable Heater,Appliances,Climate,1,93.25,0.0,93.25,66.55,26.70,Credit Card,Completed,Express,2.0,No,Emma Carter,5.0,52.0,2022
16887,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,London City,United Kingdom,England,London,AeroBook 14 Laptop,Electronics,Laptops,2,901.65,5.0,1713.14,1401.99,311.15,Credit Card,Processing,Standard,3.0,No,Emma Carter,4.0,107.0,2023
16888,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,London City,United Kingdom,England,London,Security Camera,Electronics,Cameras,1,159.93,10.0,143.93,116.02,27.91,Apple Pay,Completed,Standard,6.0,No,Sophia Brown,2.0,58.0,2025
16889,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Notebook Pack,Office Supplies,Paper,2,27.20,0.0,54.41,32.71,21.70,Debit Card,Completed,Standard,7.0,No,Noah Wilson,3.0,32.0,2022
16890,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,Toronto Central,Canada,Ontario,Toronto,Backup Drive 2TB,Electronics,Storage,1,139.31,0.0,139.31,102.21,37.10,PayPal,Completed,Pickup,0.0,No,Grace Harris,5.0,73.0,2025

In [28]:
df.reset_index(drop=True)

,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
0,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,Los Angeles Downtown,United States,West,LOS ANGELES,Webcam HD,Electronics,Cameras,2,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81.0,2022
1,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123.0,2024
2,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93.0,2024
3,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11,115.34,15.0,1078.46,897.91,180.55,paypal,Completed,Next Day,2.0,No,Grace Harris,NaN,59.0,2025
4,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16886,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,Sydney CBD,Australia,New South Wales,Sydney,Portable Heater,Appliances,Climate,1,93.25,0.0,93.25,66.55,26.70,Credit Card,Completed,Express,2.0,No,Emma Carter,5.0,52.0,2022
16887,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,London City,United Kingdom,England,London,AeroBook 14 Laptop,Electronics,Laptops,2,901.65,5.0,1713.14,1401.99,311.15,Credit Card,Processing,Standard,3.0,No,Emma Carter,4.0,107.0,2023
16888,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,London City,United Kingdom,England,London,Security Camera,Electronics,Cameras,1,159.93,10.0,143.93,116.02,27.91,Apple Pay,Completed,Standard,6.0,No,Sophia Brown,2.0,58.0,2025
16889,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Notebook Pack,Office Supplies,Paper,2,27.20,0.0,54.41,32.71,21.70,Debit Card,Completed,Standard,7.0,No,Noah Wilson,3.0,32.0,2022
16890,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,Toronto Central,Canada,Ontario,Toronto,Backup Drive 2TB,Electronics,Storage,1,139.31,0.0,139.31,102.21,37.10,PayPal,Completed,Pickup,0.0,No,Grace Harris,5.0,73.0,2025

In [29]:
df.isna().mean().round(2)*100

Customer_Name            0.0
Customer_Age             0.0
Customer_Gender          0.0
Customer_Segment         0.0
Order_Date               0.0
Order_Time               0.0
Sales_Channel            0.0
Store_Name               0.0
Country                  0.0
Region                   0.0
City                     0.0
Product_Name             0.0
Product_Category         0.0
Product_Subcategory      0.0
Quantity                 0.0
Unit_Price               0.0
Discount_Percentage      0.0
Sales_Amount             0.0
Cost_Amount              0.0
Profit                   0.0
Payment_Method           0.0
Order_Status             0.0
Shipping_Method          0.0
Delivery_Days            0.0
Return_Flag              0.0
Sales_Representative     0.0
Customer_Rating         19.0
Inventory_Level          0.0
Order_Year               0.0
dtype: float64

### Filling Customer_Rating

In [37]:
Customer_Rating_Mean=df['Customer_Rating'].mean().round(1)
df['Customer_Rating'] = df['Customer_Rating'].fillna(Customer_Rating_Mean)
df.head()

,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
0,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,Los Angeles Downtown,United States,West,LOS ANGELES,Webcam HD,Electronics,Cameras,2,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81.0,2022
1,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123.0,2024
2,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93.0,2024
3,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11,115.34,15.0,1078.46,897.91,180.55,paypal,Completed,Next Day,2.0,No,Grace Harris,4.0,59.0,2025
4,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56.0,2022

In [38]:
df.isna().mean().round(2)*100

Customer_Name           0.0
Customer_Age            0.0
Customer_Gender         0.0
Customer_Segment        0.0
Order_Date              0.0
Order_Time              0.0
Sales_Channel           0.0
Store_Name              0.0
Country                 0.0
Region                  0.0
City                    0.0
Product_Name            0.0
Product_Category        0.0
Product_Subcategory     0.0
Quantity                0.0
Unit_Price              0.0
Discount_Percentage     0.0
Sales_Amount            0.0
Cost_Amount             0.0
Profit                  0.0
Payment_Method          0.0
Order_Status            0.0
Shipping_Method         0.0
Delivery_Days           0.0
Return_Flag             0.0
Sales_Representative    0.0
Customer_Rating         0.0
Inventory_Level         0.0
Order_Year              0.0
dtype: float64