In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
df=pd.read_csv('Database/Sales_transactions_2022_2025.csv')
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
18041,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
18042,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
18043,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
18044,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

| Name | Description |
|------|-------------|
| Transaction_ID | Unique ID of one sales line |
| Order_ID | Order/basket ID; one order can have several rows |
| Customer_ID | Customer identifier (use this instead of the name) |
| Customer_Name | Customer full name; not a reliable key |
| Customer_Age | Customer age in years |
| Customer_Gender | Female / Male / Non-binary |
| Customer_Segment | Consumer, Small Business, Corporate, Premium, New Customer, Returning Customer |
| Order_Date | Date the order was placed |
| Order_Time | Time of day the order was placed |
| Sales_Channel | Online, Retail Store, B2B Portal, Phone Order |
| Store_ID | Store code |
| Store_Name | Store name (1-to-1 with Store_ID) |
| Country | Country of the store |
| Region | State / province / region |
| City | City of the store |
| Product_ID | Product code (28 products) |
| Product_Name | Product name (1-to-1 with Product_ID) |
| Product_Category | Electronics, Office Supplies, Furniture, Appliances |
| Product_Subcategory | Detailed group inside the category |
| Quantity | Units sold on the line |
| Unit_Price | List price per unit before discount |
| Discount_Percentage | Discount applied, in % |
| Sales_Amount | Revenue = Quantity × Unit_Price × (1 − Discount/100) |
| Cost_Amount | Total cost of goods for the line |
| Profit | Sales_Amount − Cost_Amount (negative = loss) |
| Payment_Method | Credit Card, Debit Card, PayPal, Bank Transfer, Apple Pay, Cash |
| Order_Status | Completed, Shipped, Processing, Returned, Cancelled |
| Shipping_Method | Standard, Express, Next Day, Pickup |
| Delivery_Days | Days from order to delivery (0 = same day / pickup) |
| Return_Flag | Yes / No: was the item returned |
| Return_Reason | Why it was returned; empty when Return_Flag = No |
| Sales_Representative | Sales rep who handled the order |
| Promotion_Code | Promo code used; empty = no promotion |
| Customer_Rating | Satisfaction score, 1 (worst) to 5 (best) |
| Inventory_Level | Stock units on hand at the time of sale |
| Order_Year | Year taken from Order_Date (2022–2025) |

## Data Exploration

In [4]:
df.columns

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Age', 'Customer_Gender', 'Customer_Segment', 'Order_Date',
       'Order_Time', 'Sales_Channel', 'Store_ID', 'Store_Name', 'Country',
       'Region', 'City', 'Product_ID', 'Product_Name', 'Product_Category',
       'Product_Subcategory', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Method',
       'Order_Status', 'Shipping_Method', 'Delivery_Days', 'Return_Flag',
       'Return_Reason', 'Sales_Representative', 'Promotion_Code',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='object')

# Check Data Types

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18045 entries, 0 to 18044
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction_ID        18045 non-null  object
 1   Order_ID              18045 non-null  object
 2   Customer_ID           18045 non-null  object
 3   Customer_Name         17937 non-null  object
 4   Customer_Age          17827 non-null  float64
 5   Customer_Gender       17883 non-null  object
 6   Customer_Segment      18045 non-null  object
 7   Order_Date            18045 non-null  object
 8   Order_Time            18045 non-null  object
 9   Sales_Channel         18045 non-null  object
 10  Store_ID              18045 non-null  object
 11  Store_Name            18045 non-null  object
 12  Country               18045 non-null  object
 13  Region                18045 non-null  object
 14  City                  18045 non-null  object
 15  Product_ID            18045 non-null  object
 16  Product_Name          17901 non-null  object
 17  Product_Category      18045 non-null  object
 18  Product_Subcategory   18045 non-null  object
 19  Quantity              18045 non-null  int64
 20  Unit_Price            18045 non-null  float64
 21  Discount_Percentage   18045 non-null  float64
 22  Sales_Amount          18045 non-null  float64
 23  Cost_Amount           18045 non-null  float64
 24  Profit                18045 non-null  float64
 25  Payment_Method        17898 non-null  object
 26  Order_Status          18045 non-null  object
 27  Shipping_Method       18045 non-null  object
 28  Delivery_Days         17883 non-null  float64
 29  Return_Flag           18045 non-null  object
 30  Return_Reason         1877 non-null   object
 31  Sales_Representative  18045 non-null  object
 32  Promotion_Code        8308 non-null   object
 33  Customer_Rating       14610 non-null  float64
 34  Inventory_Level       17847 non-null  float64
 35  Order_Year            18045 non-null  int64
dtypes: float64(9), int64(2), object(25)
memory usage: 5.0+ MB

# 2- Check duplicates

In [6]:
df.duplicated().sum()

np.int64(45)

In [7]:
df[df.duplicated()]

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
602,T02009714,O0109714,C04340,Mia Anderson,52.0,Female,Consumer,2025-11-13,11:39:31,Phone Order,...,Completed,Next Day,4.0,No,NaN,Ella Lewis,SAVE10,5.0,93.0,2025
3868,T02003428,O0103428,C01135,Leo Green,NaN,Female,Corporate,2022-10-09,17:17:30,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Amelia Jackson,NaN,5.0,74.0,2022
4133,T02004930,O0104930,C00123,Grace Nelson,44.0,Female,Corporate,2023-04-17,10:07:47,Phone Order,...,Completed,Standard,2.0,No,NaN,Liam Davis,BACK2WORK,5.0,58.0,2023
4471,T02000103,O0100051,C02559,James Williams,34.0,Male,Returning Customer,2022-04-05,15:41:57,B2B Portal,...,Completed,Standard,7.0,No,NaN,Amelia Jackson,SAVE10,5.0,79.0,2022
6568,T02002644,O0102644,C01805,David Moore,43.0,Male,Consumer,2022-06-09,15:52:08,B2B Portal,...,Completed,Pickup,0.0,No,NaN,Olivia Martin,NaN,4.0,106.0,2022
7041,T02010013,O0105006,C05246,Ella Hall,34.0,Male,Consumer,2024-05-08,10:27:59,Retail Store,...,Completed,Pickup,0.0,No,NaN,Ella Lewis,NaN,4.0,86.0,2024
7069,T02015002,O0115002,C04984,Benjamin Thompson,31.0,Male,Corporate,2023-06-06,18:26:27,Retail Store,...,Returned,Pickup,0.0,Yes,Other,Lucas Moore,NaN,5.0,53.0,2023
7504,T02008527,O0108527,C03964,Jack Miller,42.0,Male,Returning Customer,2025-11-28,16:35:25,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Lucas Moore,NaN,5.0,84.0,2025
7675,T02008170,O0104085,C00246,Ava Taylor,40.0,Male,Returning Customer,2024-11-28,11:01:16,B2B Portal,...,Cancelled,Pickup,0.0,No,NaN,Amelia Jackson,SPRING15,4.0,42.0,2024
7914,T02005299,O0105299,C05437,Noah Thompson,18.0,FEMALE,Corporate,2024-04-21,09:53:02,Retail Store,...,Shipped,Pickup,0.0,No,NaN,James Anderson,NaN,4.0,123.0,2024
7923,T02004986,O0104986,C02621,Benjamin Walker,62.0,Male,New Customer,2022-03-17,13:45:50,Online,...,Completed,Express,1.0,No,NaN,Liam Davis,BLACKFRIDAY25,4.0,46.0,2022
8825,T02007889,O0107889,C02127,William Taylor,18.0,Female,Premium,2024-05-03,18:47:59,Online,...,Processing,Standard,3.0,No,NaN,Ella Lewis,NaN,3.0,95.0,2024
9039,T02004225,O0104225,C00072,Jack Smith,47.0,Male,Returning Customer,2024-06-27,17:28:51,Online,...,Shipped,Standard,4.0,No,NaN,Michael Clark,NaN,4.0,58.0,2024
9128,T02008291,O0108291,C02549,Ava Walker,39.0,Male,Small Business,2023-01-03,18:36:00,Online,...,Returned,Standard,7.0,Yes,Wrong Item,James Anderson,NaN,2.0,77.0,2023
9590,T02017285,O0117285,C03739,Grace Hall,38.0,Female,Consumer,2024-05-28,11:47:50,Retail Store,...,Completed,Standard,4.0,No,NaN,Henry White,NaN,4.0,73.0,2024
9835,T02000746,O0100373,C04097,Grace Thompson,39.0,Female,Small Business,2025-09-22,13:30:26,Retail Store,...,Completed,Pickup,0.0,No,NaN,Ella Lewis,NaN,5.0,84.0,2025
10113,T02003264,O0103264,C00168,Alexander Wright,48.0,Female,Consumer,2025-12-09,14:54:24,Online,...,Completed,Standard,6.0,No,NaN,Michael Clark,MOM15,4.0,54.0,2025
10391,T02009907,O0109907,C03188,William Smith,18.0,Male,Corporate,2023-11-13,16:13:03,B2B Portal,...,Completed,Pickup,0.0,No,NaN,Michael Clark,NaN,NaN,53.0,2023
10705,T02003151,O0101575,C03525,Emma King,51.0,Female,New Customer,2022-10-06,17:20:13,Online,...,Completed,Next Day,1.0,No,NaN,Henry White,NaN,NaN,95.0,2022
10767,T02004194,O0102097,C05378,Olivia Williams,56.0,Female,Corporate,2022-05-17,15:42:53,Online,...,Processing,Next Day,1.0,No,NaN,Mia Taylor,NaN,5.0,100.0,2022
10924,T02005256,O0105256,C00930,Amelia Allen,57.0,Male,Corporate,2023-11-26,16:01:04,Phone Order,...,Cancelled,Standard,6.0,No,NaN,Noah Wilson,NaN,3.0,107.0,2023
10972,T02001529,O0101529,C01893,David Thomas,41.0,Male,Consumer,2022-12-20,11:59:46,B2B Portal,...,Completed,Standard,3.0,No,NaN,Michael Clark,NaN,3.0,86.0,2022
11014,T02003561,O0103561,C03829,Freya Brown,58.0,Female,Consumer,2025-12-12,16:35:32,Online,...,Completed,Express,1.0,No,NaN,Ella Lewis,NaN,5.0,63.0,2025
11498,T02015436,O0115436,C00771,Amelia King,NaN,Male,Premium,2023-05-30,18:21:47,Online,...,Completed,Pickup,0.0,No,NaN,Liam Davis,BACK2WORK,5.0,54.0,2023
11514,T02003202,O0101601,C01986,Amelia Walker,47.0,Male,Returning Customer,2023-02-23,16:04:52,Online,...,Returned,Standard,3.0,Yes,Wrong Item,Charlotte Thomas,SPRING15,5.0,68.0,2023
11587,T02007846,O0107846,C03255,David Miller,48.0,Male,Corporate,2023-11-17,11:00:35,Retail Store,...,Completed,Pickup,0.0,No,NaN,Henry White,NaN,3.0,85.0,2023
12487,T02006187,O0103093,C03389,Amelia Allen,36.0,Female,Small Business,2022-03-16,16:31:48,Retail Store,...,Returned,Standard,3.0,Yes,Wrong Item,Emma Carter,HALLOWEEN15,1.0,98.0,2022
12490,T02000375,O0100375,C04190,Theo Clark,18.0,Female,Returning Customer,2025-09-29,14:45:26,Online,...,Completed,Standard,7.0,No,NaN,Grace Harris,NaN,2.0,67.0,2025
12499,T02012758,O0112758,C04888,Evelyn Moore,21.0,Female,Small Business,2024-08-26,18:13:27,Online,...,Shipped,Standard,3.0,No,NaN,Noah Wilson,NaN,NaN,73.0,2024
13176,T02002892,O0102892,C04336,Grace Davis,18.0,Female,Premium,2025-11-04,10:38:11,Retail Store,...,Completed,Pickup,0.0,No,NaN,Noah Wilson,MOM15,3.0,76.0,2025
13325,T02016423,O0116423,C05597,Max Thomas,33.0,Female,Small Business,2023-05-04,11:55:11,Phone Order,...,Cancelled,Pickup,0.0,No,NaN,Daniel Miller,NaN,4.0,66.0,2023
13441,T02015596,O0115596,C05463,Samuel Adams,50.0,Female,Corporate,2024-04-27,15:42:38,Online,...,Completed,Standard,1.0,No,NaN,Liam Davis,BLACKFRIDAY25,5.0,85.0,2024
13940,T02012050,O0112050,C05094,Samuel Johnson,38.0,Male,Corporate,2024-12-13,13:55:03,Online,...,Shipped,Standard,8.0,No,NaN,James Anderson,NaN,3.0,104.0,2024
14210,T02002832,O0102832,C05359,Max Thomas,37.0,Female,Corporate,2023-01-13,12:18:23,B2B Portal,...,Completed,Express,1.0,No,NaN,Amelia Jackson,VALENTINE20,5.0,34.0,2023
14400,T02004731,O0104731,C05226,Lucas Williams,32.0,Female,Consumer,2024-12-23,18:14:24,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Amelia Jackson,NaN,5.0,55.0,2024
15022,T02005072,O0102536,C03265,Henry White,31.0,Female,Consumer,2025-12-18,13:27:41,Retail Store,...,Completed,Pickup,0.0,No,NaN,Charlotte Thomas,HOLIDAY20,3.0,59.0,2025
15259,T02005853,O0105853,C03490,David Thomas,47.0,Female,Consumer,2022-10-18,13:42:31,Retail Store,...,Completed,Pickup,0.0,No,NaN,Olivia Martin,MOM15,NaN,111.0,2022
15799,T02000689,O0100344,C01832,Olivia Walker,32.0,Male,Small Business,2022-04-30,17:47:27,Retail Store,...,Completed,Standard,5.0,No,NaN,Grace Harris,NaN,3.0,60.0,2022
15977,T02006502,O0106502,C05481,Lucas Green,49.0,Male,Small Business,2024-02-17,19:11:35,Online,...,Completed,Standard,5.0,No,NaN,Henry White,BACK2WORK,5.0,44.0,2024
16063,T02017513,O0117513,C03757,Ella Nelson,29.0,Female,Corporate,2024-09-16,16:20:06,B2B Portal,...,Completed,Next Day,2.0,No,NaN,David Walker,NaN,NaN,34.0,2024
16127,T02005710,O0105710,C02007,Hannah King,50.0,Male,Small Business,2025-08-10,14:13:20,B2B Portal,...,Processing,Next Day,1.0,No,NaN,Daniel Miller,HOLIDAY20,5.0,71.0,2025
16787,T02013564,O0113564,C01107,Arthur White,27.0,Female,Corporate,2025-08-09,19:56:18,Online,...,Completed,Standard,6.0,No,NaN,Mia Taylor,VALENTINE20,4.0,54.0,2025
17469,T02017831,O0117831,C02820,Thomas Nelson,63.0,Non-binary,Corporate,2024-09-30,17:35:33,Retail Store,...,Cancelled,Pickup,0.0,No,NaN,Mia Taylor,CORP5,5.0,53.0,2024
17624,T02000929,O0100929,C02671,Thomas Baker,31.0,Non-binary,Consumer,2024-11-16,17:28:09,Retail Store,...,Completed,Pickup,0.0,No,NaN,Michael Clark,MOM15,5.0,101.0,2024
17985,T02000019,O0100009,C02496,Chloe Williams,26.0,Male,Consumer,2024-07-15,14:32:58,B2B Portal,...,Cancelled,Standard,4.0,No,NaN,Michael Clark,HOLIDAY20,4.0,120.0,2024

# Drop duplicates

In [8]:
df = df.drop_duplicates()
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
18041,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
18042,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
18043,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
18044,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

In [9]:
df= df.reset_index(drop=True)
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
17996,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
17997,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
17998,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
17999,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

## 3 - Check summary for numerical values

In [10]:
df.describe().round(1)

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17784.0,18000.0,18000.0,18000.0,18000.0,18000.0,18000.0,17838.0,14570.0,17802.0,18000.0
mean,38.9,2.1,232.8,6.3,457.4,366.1,91.4,2.3,4.0,70.2,2023.6
std,10.7,1.8,294.2,6.9,857.1,706.3,167.9,2.3,1.0,22.0,1.1
min,4.0,-3.0,21.4,0.0,16.7,12.2,-299.3,0.0,1.0,0.0,2022.0
25%,32.0,1.0,53.0,0.0,78.5,56.1,19.5,0.0,4.0,55.0,2023.0
50%,39.0,2.0,99.8,5.0,168.8,122.3,40.2,1.0,4.0,70.0,2024.0
75%,46.0,3.0,285.8,10.0,472.7,376.1,93.3,4.0,5.0,85.0,2025.0
max,112.0,11.0,1425.1,110.0,14303.1,10791.0,3512.1,10.0,5.0,157.0,2025.0

## 4 - Check summary for categorical values

In [11]:
df.describe(include= ['object'])

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,Store_ID,...,Product_Name,Product_Category,Product_Subcategory,Payment_Method,Order_Status,Shipping_Method,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code
count,18000,18000,18000,17892,17838,18000,18000,18000,18000,18000,...,17856,18000,18000,17856,18000,18000,18000,1873,18000,8288
unique,18000,14541,4882,1179,6,6,1461,15201,4,12,...,28,7,17,10,8,4,2,6,16,10
top,T02016694,O0107988,C02559,Amelia King,Female,Consumer,2024-12-25,12:29:48,Online,NYC-01,...,Copy Paper Box,Electronics,Accessories,Credit Card,Completed,Standard,No,Late Delivery,Sophia Brown,HOLIDAY20
freq,1,3,20,57,8720,8027,33,5,8195,2170,...,975,8121,3236,6725,11436,7735,16127,331,1166,1396

In [12]:
df['Customer_Gender'].unique()

array(['Male', 'Female', 'Non-binary', 'male', 'FEMALE', nan,
       'Non Binary'], dtype=object)

In [13]:
df.head()

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022

## 4-Check Missing Values

In [14]:
df.isna().sum()

Transaction_ID              0
Order_ID                    0
Customer_ID                 0
Customer_Name             108
Customer_Age              216
Customer_Gender           162
Customer_Segment            0
Order_Date                  0
Order_Time                  0
Sales_Channel               0
Store_ID                    0
Store_Name                  0
Country                     0
Region                      0
City                        0
Product_ID                  0
Product_Name              144
Product_Category            0
Product_Subcategory         0
Quantity                    0
Unit_Price                  0
Discount_Percentage         0
Sales_Amount                0
Cost_Amount                 0
Profit                      0
Payment_Method            144
Order_Status                0
Shipping_Method             0
Delivery_Days             162
Return_Flag                 0
Return_Reason           16127
Sales_Representative        0
Promotion_Code           9712
Customer_Rating          3430
Inventory_Level           198
Order_Year                  0
dtype: int64

In [15]:
df.isna().mean().round(2)*100

Transaction_ID           0.0
Order_ID                 0.0
Customer_ID              0.0
Customer_Name            1.0
Customer_Age             1.0
Customer_Gender          1.0
Customer_Segment         0.0
Order_Date               0.0
Order_Time               0.0
Sales_Channel            0.0
Store_ID                 0.0
Store_Name               0.0
Country                  0.0
Region                   0.0
City                     0.0
Product_ID               0.0
Product_Name             1.0
Product_Category         0.0
Product_Subcategory      0.0
Quantity                 0.0
Unit_Price               0.0
Discount_Percentage      0.0
Sales_Amount             0.0
Cost_Amount              0.0
Profit                   0.0
Payment_Method           1.0
Order_Status             0.0
Shipping_Method          0.0
Delivery_Days            1.0
Return_Flag              0.0
Return_Reason           90.0
Sales_Representative     0.0
Promotion_Code          54.0
Customer_Rating         19.0
Inventory_Level          1.0
Order_Year               0.0
dtype: float64

In [16]:
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
17996,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
17997,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
17998,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
17999,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

## 5- Cleaning data

### Droping unnecessary Columns

In [17]:
df=df.drop (['Transaction_ID','Order_ID','Store_ID','Product_ID','Return_Reason','Promotion_Code', 'Order_Time'],axis=1 )

In [18]:
pd.set_option('display.max_columns',None)

In [19]:
df.describe().round(2)

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17784.00,18000.00,18000.00,18000.00,18000.00,18000.00,18000.00,17838.00,14570.00,17802.00,18000.00
mean,38.92,2.13,232.78,6.25,457.45,366.13,91.41,2.26,3.99,70.25,2023.57
std,10.72,1.78,294.25,6.88,857.10,706.34,167.86,2.32,1.01,22.04,1.12
min,4.00,-3.00,21.39,0.00,16.68,12.17,-299.31,0.00,1.00,0.00,2022.00
25%,32.00,1.00,52.96,0.00,78.53,56.10,19.49,0.00,4.00,55.00,2023.00
50%,39.00,2.00,99.84,5.00,168.84,122.32,40.19,1.00,4.00,70.00,2024.00
75%,46.00,3.00,285.78,10.00,472.74,376.14,93.30,4.00,5.00,85.00,2025.00
max,112.00,11.00,1425.09,110.00,14303.07,10791.00,3512.08,10.00,5.00,157.00,2025.00

In [20]:
df.describe(include='object')

,Customer_ID,Customer_Name,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Payment_Method,Order_Status,Shipping_Method,Return_Flag,Sales_Representative
count,18000,17892,17838,18000,18000,18000,18000,18000,18000,18000,17856,18000,18000,17856,18000,18000,18000,18000
unique,4882,1179,6,6,1461,4,12,6,14,15,28,7,17,10,8,4,2,16
top,C02559,Amelia King,Female,Consumer,2024-12-25,Online,New York Central,United States,England,New York,Copy Paper Box,Electronics,Accessories,Credit Card,Completed,Standard,No,Sophia Brown
freq,20,57,8720,8027,33,8195,2170,7526,2974,2156,975,8121,3236,6725,11436,7735,16127,1166

In [21]:
df.isna().mean().round(2)*100

Customer_ID              0.0
Customer_Name            1.0
Customer_Age             1.0
Customer_Gender          1.0
Customer_Segment         0.0
Order_Date               0.0
Sales_Channel            0.0
Store_Name               0.0
Country                  0.0
Region                   0.0
City                     0.0
Product_Name             1.0
Product_Category         0.0
Product_Subcategory      0.0
Quantity                 0.0
Unit_Price               0.0
Discount_Percentage      0.0
Sales_Amount             0.0
Cost_Amount              0.0
Profit                   0.0
Payment_Method           1.0
Order_Status             0.0
Shipping_Method          0.0
Delivery_Days            1.0
Return_Flag              0.0
Sales_Representative     0.0
Customer_Rating         19.0
Inventory_Level          1.0
Order_Year               0.0
dtype: float64

#### Drop NA in Rows

In [22]:
df=df.dropna(subset= ['Customer_Name', 'Customer_Age','Customer_Gender','Product_Name','Payment_Method','Delivery_Days','Inventory_Level'], ignore_index= True)
df

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
0,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,Online,Los Angeles Downtown,United States,West,LOS ANGELES,Webcam HD,Electronics,Cameras,2,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81.0,2022
1,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123.0,2024
2,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93.0,2024
3,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11,115.34,15.0,1078.46,897.91,180.55,paypal,Completed,Next Day,2.0,No,Grace Harris,NaN,59.0,2025
4,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16886,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,Online,Sydney CBD,Australia,New South Wales,Sydney,Portable Heater,Appliances,Climate,1,93.25,0.0,93.25,66.55,26.70,Credit Card,Completed,Express,2.0,No,Emma Carter,5.0,52.0,2022
16887,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,Retail Store,London City,United Kingdom,England,London,AeroBook 14 Laptop,Electronics,Laptops,2,901.65,5.0,1713.14,1401.99,311.15,Credit Card,Processing,Standard,3.0,No,Emma Carter,4.0,107.0,2023
16888,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,Online,London City,United Kingdom,England,London,Security Camera,Electronics,Cameras,1,159.93,10.0,143.93,116.02,27.91,Apple Pay,Completed,Standard,6.0,No,Sophia Brown,2.0,58.0,2025
16889,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Notebook Pack,Office Supplies,Paper,2,27.20,0.0,54.41,32.71,21.70,Debit Card,Completed,Standard,7.0,No,Noah Wilson,3.0,32.0,2022
16890,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,Retail Store,Toronto Central,Canada,Ontario,Toronto,Backup Drive 2TB,Electronics,Storage,1,139.31,0.0,139.31,102.21,37.10,PayPal,Completed,Pickup,0.0,No,Grace Harris,5.0,73.0,2025

In [23]:
df.isna().mean().round(2)*100

Customer_ID              0.0
Customer_Name            0.0
Customer_Age             0.0
Customer_Gender          0.0
Customer_Segment         0.0
Order_Date               0.0
Sales_Channel            0.0
Store_Name               0.0
Country                  0.0
Region                   0.0
City                     0.0
Product_Name             0.0
Product_Category         0.0
Product_Subcategory      0.0
Quantity                 0.0
Unit_Price               0.0
Discount_Percentage      0.0
Sales_Amount             0.0
Cost_Amount              0.0
Profit                   0.0
Payment_Method           0.0
Order_Status             0.0
Shipping_Method          0.0
Delivery_Days            0.0
Return_Flag              0.0
Sales_Representative     0.0
Customer_Rating         19.0
Inventory_Level          0.0
Order_Year               0.0
dtype: float64

### Filling Customer_Rating

In [24]:
Customer_Rating_Mean=df['Customer_Rating'].mean().round(1)
Customer_Rating_Mean

np.float64(4.0)

In [25]:
df['Customer_Rating'].median()

np.float64(4.0)

In [26]:
px.histogram(data_frame= df, x = 'Customer_Rating',text_auto= True,
       title= 'Customer_Rating')

#### Filling The NA in 'Customer_Rating' With Median or Mean which Represented 19 % out of the Data will give an higher output to the Rating 4 which will not give a smooth Distribution so alternatively we can use KNN imputer for numerical columns to fill NAN's

In [27]:
num_cols = df.select_dtypes(include= 'number').columns
num_cols

Index(['Customer_Age', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Delivery_Days',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='object')

In [28]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors= 5)

df[num_cols] = knn.fit_transform(df[num_cols])

In [29]:
px.histogram(data_frame= df, x = 'Customer_Rating',text_auto= True,
       title= 'Customer_Rating')

In [30]:
df.isna().mean().round(2)*100

Customer_ID             0.0
Customer_Name           0.0
Customer_Age            0.0
Customer_Gender         0.0
Customer_Segment        0.0
Order_Date              0.0
Sales_Channel           0.0
Store_Name              0.0
Country                 0.0
Region                  0.0
City                    0.0
Product_Name            0.0
Product_Category        0.0
Product_Subcategory     0.0
Quantity                0.0
Unit_Price              0.0
Discount_Percentage     0.0
Sales_Amount            0.0
Cost_Amount             0.0
Profit                  0.0
Payment_Method          0.0
Order_Status            0.0
Shipping_Method         0.0
Delivery_Days           0.0
Return_Flag             0.0
Sales_Representative    0.0
Customer_Rating         0.0
Inventory_Level         0.0
Order_Year              0.0
dtype: float64

In [31]:
df.describe().round(1)

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,16891.0,16891.0,16891.0,16891.0,16891.0,16891.0,16891.0,16891.0,16891.0,16891.0,16891.0
mean,38.9,2.1,233.3,6.3,458.7,367.1,91.7,2.3,4.0,70.2,2023.6
std,10.7,1.8,294.9,6.9,856.3,706.2,167.3,2.3,0.9,22.0,1.1
min,4.0,-3.0,21.4,0.0,16.7,12.2,-299.3,0.0,1.0,0.0,2022.0
25%,32.0,1.0,54.7,0.0,78.5,56.1,19.5,0.0,3.8,55.0,2023.0
50%,39.0,2.0,100.0,5.0,169.3,122.8,40.3,1.0,4.0,70.0,2024.0
75%,46.0,3.0,286.2,10.0,473.3,377.5,93.5,4.0,5.0,85.0,2025.0
max,112.0,11.0,1425.1,110.0,14303.1,10791.0,3512.1,10.0,5.0,157.0,2025.0

### - Changing Columns data type

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16891 entries, 0 to 16890
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           16891 non-null  object
 1   Customer_Name         16891 non-null  object
 2   Customer_Age          16891 non-null  float64
 3   Customer_Gender       16891 non-null  object
 4   Customer_Segment      16891 non-null  object
 5   Order_Date            16891 non-null  object
 6   Sales_Channel         16891 non-null  object
 7   Store_Name            16891 non-null  object
 8   Country               16891 non-null  object
 9   Region                16891 non-null  object
 10  City                  16891 non-null  object
 11  Product_Name          16891 non-null  object
 12  Product_Category      16891 non-null  object
 13  Product_Subcategory   16891 non-null  object
 14  Quantity              16891 non-null  float64
 15  Unit_Price            16891 non-null  float64
 16  Discount_Percentage   16891 non-null  float64
 17  Sales_Amount          16891 non-null  float64
 18  Cost_Amount           16891 non-null  float64
 19  Profit                16891 non-null  float64
 20  Payment_Method        16891 non-null  object
 21  Order_Status          16891 non-null  object
 22  Shipping_Method       16891 non-null  object
 23  Delivery_Days         16891 non-null  float64
 24  Return_Flag           16891 non-null  object
 25  Sales_Representative  16891 non-null  object
 26  Customer_Rating       16891 non-null  float64
 27  Inventory_Level       16891 non-null  float64
 28  Order_Year            16891 non-null  float64
dtypes: float64(11), object(18)
memory usage: 3.7+ MB

In [33]:
df[['Customer_Age','Inventory_Level','Quantity','Order_Year']]=df[['Customer_Age','Inventory_Level','Quantity','Order_Year']].astype('int')

In [34]:
df['Order_Date']=pd.to_datetime(df['Order_Date'])

In [35]:
df.head()

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
0,C01482,Sophia Smith,28,Male,Consumer,2022-10-06,Online,Los Angeles Downtown,United States,West,LOS ANGELES,Webcam HD,Electronics,Cameras,2,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81,2022
1,C01591,Hannah King,46,Female,Consumer,2024-06-03,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123,2024
2,C04140,Emma Wilson,42,Male,Consumer,2024-12-19,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93,2024
3,C03663,Daniel Clark,18,Male,Corporate,2025-10-05,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11,115.34,15.0,1078.46,897.91,180.55,paypal,Completed,Next Day,2.0,No,Grace Harris,4.0,59,2025
4,C02749,Sophia Smith,37,Male,Returning Customer,2022-09-13,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56,2022

### - In-Depth check of numerical , categorical columns

In [36]:
Categorical_column= df.select_dtypes(include= 'object').columns
Categorical_column

Index(['Customer_ID', 'Customer_Name', 'Customer_Gender', 'Customer_Segment',
       'Sales_Channel', 'Store_Name', 'Country', 'Region', 'City',
       'Product_Name', 'Product_Category', 'Product_Subcategory',
       'Payment_Method', 'Order_Status', 'Shipping_Method', 'Return_Flag',
       'Sales_Representative'],
      dtype='object')

In [37]:
for col in Categorical_column:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('\n', '-' * 100, '\n')

Customer_ID
4810
['C01482' 'C01591' 'C04140' ... 'C01531' 'C05206' 'C03311']

 ----------------------------------------------------------------------------------------------------

Customer_Name
1177
['Sophia Smith' 'Hannah King' 'Emma Wilson' ... 'Ella King'
 'Amelia Anderson' 'Charlotte Martin']

 ----------------------------------------------------------------------------------------------------

Customer_Gender
6
['Male' 'Female' 'Non-binary' 'male' 'FEMALE' 'Non Binary']

 ----------------------------------------------------------------------------------------------------

Customer_Segment
6
['Consumer' 'Corporate' 'Returning Customer' 'New Customer'
 'Small Business' 'Premium']

 ----------------------------------------------------------------------------------------------------

Sales_Channel
4
['Online' 'B2B Portal' 'Retail Store' 'Phone Order']

 ----------------------------------------------------------------------------------------------------

Store_Name
12
['Los Angeles Downtown' 'Sydney CBD' 'Paris Central' 'New York Central'
 'Chicago Loop' 'Toronto Central' 'Vancouver West' 'Austin Business'
 'London City' 'Cologne Business' 'Manchester North' 'Munich Zentrum']

 ----------------------------------------------------------------------------------------------------

Country
6
['United States' 'Australia' 'France' 'Canada' 'United Kingdom' 'Germany']

 ----------------------------------------------------------------------------------------------------

Region
14
['West' 'New South Wales' 'Île-de-France' 'Northeast' 'Midwest' 'Ontario'
 'British Columbia' 'South' 'England' 'North Rhine-Westphalia' 'Bavaria'
 'North East' 'British columbia' 'NRW']

 ----------------------------------------------------------------------------------------------------

City
15
['LOS ANGELES' 'Sydney' 'Paris' 'New York' 'Chicago' 'Toronto' 'Vancouver'
 'Austin' 'London' 'Cologne' 'Los Angeles' 'Manchester' ' New York '
 'Munich' 'munich']

 ----------------------------------------------------------------------------------------------------

Product_Name
28
['Webcam HD' 'Office Keyboard' 'Copy Paper Box' 'SmartDock USB-C'
 'Desk Lamp' 'Ergo Footrest' 'Security Camera' 'EdgeTab 11 Tablet'
 'ProBook 16 Laptop' 'Desk Fan' 'Office Chair Pro' 'Vision 27 Monitor'
 'Backup Drive 2TB' 'Air Purifier' 'Premium Pens' 'Precision Mouse'
 'USB Power Hub' 'Printer Plus' 'Laser Toner' 'Presentation Kit'
 'AeroBook 14 Laptop' 'Notebook Pack' 'Portable Heater' 'Filing Cabinet'
 'Coffee Machine' 'Meeting Table' 'NoiseCancel Headset' 'Standing Desk']

 ----------------------------------------------------------------------------------------------------

Product_Category
7
['Electronics' 'Office Supplies' 'Furniture' 'Appliances' 'electronics'
 'FURNITURE' 'Office supplies']

 ----------------------------------------------------------------------------------------------------

Product_Subcategory
17
['Cameras' 'Accessories' 'Paper' 'Lighting' 'Office Furniture' 'Tablets'
 'Laptops' 'Climate' 'Monitors' 'Storage' 'Home Office' 'Writing'
 'Printers' 'Consumables' 'Presentation' 'Kitchen' 'Audio']

 ----------------------------------------------------------------------------------------------------

Payment_Method
10
['Credit Card' 'Debit Card' 'paypal' 'Apple Pay' 'Cash' 'PayPal'
 'Bank Transfer' 'credit card' 'Bank transfer' 'DebitCard']

 ----------------------------------------------------------------------------------------------------

Order_Status
8
['Completed' 'Shipped' 'Returned' 'Processing' 'Cancelled' 'SHIPPED'
 'completed' 'processing']

 ----------------------------------------------------------------------------------------------------

Shipping_Method
4
['Standard' 'Next Day' 'Express' 'Pickup']

 ----------------------------------------------------------------------------------------------------

Return_Flag
2
['No' 'Yes']

 ----------------------------------------------------------------------------------------------------

Sales_Representative
16
['James Anderson' 'Ella Lewis' 'Liam Davis' 'Grace Harris' 'Sophia Brown'
 'Noah Wilson' 'David Walker' 'Mia Taylor' 'Amelia Jackson' 'Henry White'
 'Daniel Miller' 'Charlotte Thomas' 'Olivia Martin' 'Lucas Moore'
 'Emma Carter' 'Michael Clark']

 ----------------------------------------------------------------------------------------------------

### -Categorical columns adjusting fill data to match categorically

In [38]:

df ['Payment_Method'].replace({'credit card':'Credit Card',
                                'DebitCard':'Debit Card',
                               'Bank transfer':'Bank Transfer',
                               'paypal':'PayPal'}, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\2936224878.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['Payment_Method'].replace({'credit card':'Credit Card',

In [39]:
df ['Customer_Gender'].replace({'male' : 'Male',
                                'FEMALE':'Female',
                               'Non-binary':'Non Binary'}, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\3100964182.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['Customer_Gender'].replace({'male' : 'Male',

In [40]:
df ['City'].replace({'LOS ANGELES' : 'Los Angeles',
                     ' New York ':'New York',
                    'munich':'Munich'}, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\3426501345.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['City'].replace({'LOS ANGELES' : 'Los Angeles',

In [41]:
df ['Product_Category'].replace({'electronics' : 'Electronics',
                                 'Office supplies':'Office Supplies',
                                 'FURNITURE':'Furniture'}, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\4271021823.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['Product_Category'].replace({'electronics' : 'Electronics',

In [42]:
df ['Order_Status'].replace({'completed' : 'Completed',
                                 'SHIPPED':'Shipped',
                                 'processing':'Processing'}, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\4239492562.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['Order_Status'].replace({'completed' : 'Completed',

#### -Managing Outliers

In [43]:
numerical_cols = df.select_dtypes(include= 'number').columns
numerical_cols

Index(['Customer_Age', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Delivery_Days',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='object')

In [44]:
for col in numerical_cols:
    px.histogram(data_frame= df, x= col, title= col).show()
    px.box(data_frame= df, x= col, title= col).show()

##### Check Customer age (4 ,99 and 112 )

In [45]:
df['Customer_Age'].value_counts()

Customer_Age
38     679
37     672
39     645
33     625
41     602
36     594
43     592
40     591
35     589
44     566
42     546
18     532
32     518
31     497
34     476
47     470
45     465
46     465
48     450
30     401
29     386
28     380
50     378
49     372
27     364
26     297
51     297
52     293
25     274
54     248
53     240
24     215
55     206
23     201
21     196
57     175
22     171
56     157
20     156
58     137
19     127
59     125
62      89
61      80
60      68
63      57
64      50
65      36
67      34
68      27
75      23
66      22
69      13
70       9
73       7
74       2
112      1
15       1
4        1
99       1
Name: count, dtype: int64

In [46]:
df[df['Customer_Age'] == 4]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
16169,C00821,Sophie Wright,4,Male,Consumer,2022-11-01,Online,Vancouver West,Canada,British Columbia,Vancouver,Presentation Kit,Office Supplies,Presentation,2,86.98,10.0,156.57,118.51,38.06,Debit Card,Completed,Express,1.0,No,Grace Harris,3.0,63,2022

In [47]:
df[(df['Customer_Name'] == 'Sophie Wright')&((df['City'] == 'Vancouver'))]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
3032,C00821,Sophie Wright,27,Male,Consumer,2023-06-17,Phone Order,Vancouver West,Canada,British Columbia,Vancouver,Copy Paper Box,Office Supplies,Paper,2,44.90,5.0,85.31,71.39,13.92,Cash,Cancelled,Standard,8.0,No,Liam Davis,4.0,65,2023
6145,C03286,Sophie Wright,20,Male,Consumer,2023-09-13,Phone Order,Vancouver West,Canada,British Columbia,Vancouver,Laser Toner,Office Supplies,Consumables,2,120.18,5.0,228.35,184.40,43.95,Bank Transfer,Returned,Standard,4.0,Yes,Ella Lewis,4.0,31,2023
16169,C00821,Sophie Wright,4,Male,Consumer,2022-11-01,Online,Vancouver West,Canada,British Columbia,Vancouver,Presentation Kit,Office Supplies,Presentation,2,86.98,10.0,156.57,118.51,38.06,Debit Card,Completed,Express,1.0,No,Grace Harris,3.0,63,2022

In [48]:
df[df['Customer_Age'] == 99]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
16331,C03672,Charlotte Jackson,99,Male,Consumer,2024-08-15,Online,Los Angeles Downtown,United States,West,Los Angeles,Meeting Table,Furniture,Office Furniture,1,848.97,5.0,806.52,702.39,104.13,Debit Card,Completed,Standard,4.0,No,Emma Carter,3.4,72,2024

In [49]:
df[(df['Customer_Name'] == 'Charlotte Jackson')&((df['City'] == 'Los Angeles'))]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
10042,C03672,Charlotte Jackson,60,Male,New Customer,2022-06-20,Retail Store,Los Angeles Downtown,United States,West,Los Angeles,Office Keyboard,Electronics,Accessories,1,56.56,5.0,53.73,38.45,15.28,Bank Transfer,Completed,Pickup,0.0,No,David Walker,3.0,78,2022
10252,C03672,Charlotte Jackson,60,Male,Consumer,2022-03-20,Retail Store,Los Angeles Downtown,United States,West,Los Angeles,EdgeTab 11 Tablet,Electronics,Tablets,2,490.52,0.0,981.04,782.91,198.12,Debit Card,Completed,Pickup,0.0,No,Emma Carter,5.0,54,2022
10759,C02070,Charlotte Jackson,29,Female,Consumer,2025-06-24,Online,Los Angeles Downtown,United States,West,Los Angeles,Desk Lamp,Furniture,Lighting,1,66.78,0.0,66.78,41.05,25.73,Credit Card,Completed,Standard,3.0,No,David Walker,4.0,68,2025
12404,C03672,Charlotte Jackson,60,Male,Consumer,2025-01-27,Retail Store,Los Angeles Downtown,United States,West,Los Angeles,Webcam HD,Electronics,Cameras,4,87.41,0.0,349.65,242.04,107.61,PayPal,Completed,Pickup,0.0,Yes,Liam Davis,1.0,124,2025
12921,C02070,Charlotte Jackson,29,Female,New Customer,2022-11-18,Online,Los Angeles Downtown,United States,West,Los Angeles,EdgeTab 11 Tablet,Electronics,Tablets,3,505.47,20.0,1213.13,1228.39,-15.26,PayPal,Completed,Standard,4.0,No,Mia Taylor,3.8,74,2022
13227,C02070,Charlotte Jackson,29,Female,Consumer,2024-07-08,Retail Store,Los Angeles Downtown,United States,West,Los Angeles,Premium Pens,Office Supplies,Writing,1,25.10,0.0,25.10,14.47,10.63,PayPal,Completed,Standard,3.0,No,Noah Wilson,3.0,64,2024
16331,C03672,Charlotte Jackson,99,Male,Consumer,2024-08-15,Online,Los Angeles Downtown,United States,West,Los Angeles,Meeting Table,Furniture,Office Furniture,1,848.97,5.0,806.52,702.39,104.13,Debit Card,Completed,Standard,4.0,No,Emma Carter,3.4,72,2024

In [50]:
df[df['Customer_Age'] == 112]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
1744,C02947,Alexander Williams,112,Female,Consumer,2025-06-30,Retail Store,Toronto Central,Canada,Ontario,Toronto,ProBook 16 Laptop,Electronics,Laptops,2,1365.3,0.0,2730.6,2066.23,664.37,Credit Card,Cancelled,Standard,2.0,No,Amelia Jackson,5.0,57,2025

In [51]:
df[(df['Customer_Name'] == 'Alexander Williams')&((df['City'] == 'Toronto'))]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
1744,C02947,Alexander Williams,112,Female,Consumer,2025-06-30,Retail Store,Toronto Central,Canada,Ontario,Toronto,ProBook 16 Laptop,Electronics,Laptops,2,1365.30,0.0,2730.60,2066.23,664.37,Credit Card,Cancelled,Standard,2.0,No,Amelia Jackson,5.0,57,2025
8570,C02947,Alexander Williams,35,Female,Consumer,2025-11-01,Online,Toronto Central,Canada,Ontario,Toronto,Premium Pens,Office Supplies,Writing,5,21.99,15.0,93.47,62.77,30.70,Debit Card,Completed,Express,2.0,No,Michael Clark,4.0,77,2025
14022,C02947,Alexander Williams,35,Female,New Customer,2022-12-29,Retail Store,Toronto Central,Canada,Ontario,Toronto,USB Power Hub,Electronics,Accessories,5,47.33,5.0,224.83,153.24,71.59,Bank Transfer,Returned,Pickup,0.0,Yes,Charlotte Thomas,4.0,89,2022
14721,C02947,Alexander Williams,35,Female,Consumer,2023-01-31,Retail Store,Toronto Central,Canada,Ontario,Toronto,Coffee Machine,Appliances,Kitchen,2,225.36,0.0,450.71,328.40,122.31,Apple Pay,Completed,Pickup,0.0,No,Ella Lewis,4.0,58,2023
15318,C02947,Alexander Williams,35,Female,Consumer,2023-06-20,Online,Toronto Central,Canada,Ontario,Toronto,Laser Toner,Office Supplies,Consumables,1,116.25,0.0,116.25,90.35,25.90,Credit Card,Completed,Express,2.0,No,Lucas Moore,4.0,43,2023

### Checking the 3 outlier numbers in age and filtering data for same customer name from same city it appears that age 112 should be 35 , age 99 should be 60 , age 4 is to be 27

In [52]:
df ['Customer_Age'].replace({4 : 27,
                                 99:60,
                                 112:35}, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\4143192077.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['Customer_Age'].replace({4 : 27,

In [53]:
px.box(data_frame= df, x= 'Customer_Age', title= 'Customer_Age')

#### - Check -ve Values in Quantity

In [54]:
df['Quantity'].unique()

array([ 2,  6, 11,  4,  1,  3,  8,  5,  7,  9, 10,  0, -2, -1, -3])

In [55]:
df['Quantity'].value_counts()

Quantity
 1     8433
 2     4111
 3     2200
 4      828
 5      436
 6      219
 7      141
 9      136
 11     135
 8      128
 10     116
 0        5
-2        1
-1        1
-3        1
Name: count, dtype: int64

### Check on a different Data frame to replace -ve values

In [56]:
df_Quantity = df[df['Quantity']<1]
df_Quantity

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
864,C01879,Ella Young,29,Male,New Customer,2022-10-21,B2B Portal,Manchester North,United Kingdom,England,Manchester,Desk Fan,Appliances,Climate,0,71.76,5.0,749.88,547.19,202.69,Debit Card,Completed,Standard,3.0,No,Amelia Jackson,2.0,42,2022
3739,C04087,Theo Green,31,Female,Consumer,2025-11-29,Online,Vancouver West,Canada,British Columbia,Vancouver,Air Purifier,Appliances,Home Office,-2,341.36,20.0,273.09,255.93,17.16,Credit Card,Shipped,Standard,6.0,No,Grace Harris,5.0,102,2025
7003,C00483,Benjamin Wilson,30,Female,Small Business,2025-02-02,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Backup Drive 2TB,Electronics,Storage,-1,127.86,10.0,460.31,371.19,89.12,Debit Card,Processing,Standard,4.0,No,David Walker,4.0,68,2025
7448,C01567,Emma Harris,35,Female,Small Business,2025-09-23,Phone Order,Paris Central,France,Île-de-France,Paris,Security Camera,Electronics,Cameras,0,160.83,10.0,289.49,238.92,50.57,Credit Card,Completed,Standard,4.0,No,Liam Davis,4.0,49,2025
7798,C01751,Mia Clark,54,Male,Small Business,2022-12-28,Phone Order,Paris Central,France,Île-de-France,Paris,Laser Toner,Office Supplies,Consumables,0,113.50,10.0,306.46,264.90,41.56,Credit Card,Completed,Express,2.0,No,Sophia Brown,4.0,98,2022
11368,C02953,William White,48,Male,Corporate,2022-01-04,Online,Manchester North,United Kingdom,England,Manchester,Meeting Table,Furniture,Office Furniture,-3,913.91,5.0,868.21,727.86,140.35,Bank Transfer,Completed,Standard,4.0,No,Sophia Brown,5.0,104,2022
14328,C02271,Isla Jones,23,Male,Returning Customer,2023-12-13,Online,Toronto Central,Canada,Ontario,Toronto,EdgeTab 11 Tablet,Electronics,Tablets,0,515.94,15.0,877.10,849.25,27.86,Debit Card,Completed,Pickup,0.0,No,Liam Davis,5.0,76,2023
16467,C02223,Mia Martin,38,Male,Returning Customer,2024-11-19,Phone Order,Paris Central,France,Île-de-France,Paris,Meeting Table,Furniture,Office Furniture,0,881.13,10.0,793.02,716.64,76.38,Debit Card,Shipped,Standard,4.0,No,James Anderson,5.0,45,2024

In [57]:
def Real_Quantity (row):
    if row['Quantity'] < 1:
        return (row['Sales_Amount'] // ((1 - row['Discount_Percentage'] / 100) * row['Unit_Price']))
    else:
        return row['Quantity']  

df_Quantity['Quantity'] = df_Quantity.apply(Real_Quantity, axis=1)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\3780627699.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Quantity['Quantity'] = df_Quantity.apply(Real_Quantity, axis=1)

In [58]:
df_Quantity['Quantity']
df_Quantity

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
864,C01879,Ella Young,29,Male,New Customer,2022-10-21,B2B Portal,Manchester North,United Kingdom,England,Manchester,Desk Fan,Appliances,Climate,10.0,71.76,5.0,749.88,547.19,202.69,Debit Card,Completed,Standard,3.0,No,Amelia Jackson,2.0,42,2022
3739,C04087,Theo Green,31,Female,Consumer,2025-11-29,Online,Vancouver West,Canada,British Columbia,Vancouver,Air Purifier,Appliances,Home Office,1.0,341.36,20.0,273.09,255.93,17.16,Credit Card,Shipped,Standard,6.0,No,Grace Harris,5.0,102,2025
7003,C00483,Benjamin Wilson,30,Female,Small Business,2025-02-02,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Backup Drive 2TB,Electronics,Storage,4.0,127.86,10.0,460.31,371.19,89.12,Debit Card,Processing,Standard,4.0,No,David Walker,4.0,68,2025
7448,C01567,Emma Harris,35,Female,Small Business,2025-09-23,Phone Order,Paris Central,France,Île-de-France,Paris,Security Camera,Electronics,Cameras,1.0,160.83,10.0,289.49,238.92,50.57,Credit Card,Completed,Standard,4.0,No,Liam Davis,4.0,49,2025
7798,C01751,Mia Clark,54,Male,Small Business,2022-12-28,Phone Order,Paris Central,France,Île-de-France,Paris,Laser Toner,Office Supplies,Consumables,3.0,113.50,10.0,306.46,264.90,41.56,Credit Card,Completed,Express,2.0,No,Sophia Brown,4.0,98,2022
11368,C02953,William White,48,Male,Corporate,2022-01-04,Online,Manchester North,United Kingdom,England,Manchester,Meeting Table,Furniture,Office Furniture,0.0,913.91,5.0,868.21,727.86,140.35,Bank Transfer,Completed,Standard,4.0,No,Sophia Brown,5.0,104,2022
14328,C02271,Isla Jones,23,Male,Returning Customer,2023-12-13,Online,Toronto Central,Canada,Ontario,Toronto,EdgeTab 11 Tablet,Electronics,Tablets,2.0,515.94,15.0,877.10,849.25,27.86,Debit Card,Completed,Pickup,0.0,No,Liam Davis,5.0,76,2023
16467,C02223,Mia Martin,38,Male,Returning Customer,2024-11-19,Phone Order,Paris Central,France,Île-de-France,Paris,Meeting Table,Furniture,Office Furniture,1.0,881.13,10.0,793.02,716.64,76.38,Debit Card,Shipped,Standard,4.0,No,James Anderson,5.0,45,2024

In [59]:
df['Quantity']= df.apply(Real_Quantity,axis=1)

In [60]:
df['Quantity'].value_counts()

Quantity
1.0     8436
2.0     4112
3.0     2201
4.0      829
5.0      436
6.0      219
7.0      141
9.0      136
11.0     135
8.0      128
10.0     117
0.0        1
Name: count, dtype: int64

### Applied the function to Main df all Quantities are changed to logic numbers except a number is zero will be replaced to 1

In [61]:
df ['Quantity'].replace({0 : 1 }, inplace= True)

C:\Users\civil\AppData\Local\Temp\ipykernel_7708\2615931907.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df ['Quantity'].replace({0 : 1 }, inplace= True)

In [62]:
df['Quantity'].unique()

array([ 2.,  6., 11.,  4.,  1.,  3.,  8.,  5.,  7.,  9., 10.])

#### Discount Percentage >100%

In [63]:
df['Discount_Percentage'].value_counts()

Discount_Percentage
0.0      7155
5.0      3369
10.0     3017
15.0     2021
20.0     1021
25.0      295
30.0       10
45.0        1
60.0        1
110.0       1
Name: count, dtype: int64

In [64]:
df[df['Discount_Percentage']==110]

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year
16177,C02934,Lily Hall,22,Female,Returning Customer,2024-05-08,Retail Store,Sydney CBD,Australia,New South Wales,Sydney,Webcam HD,Electronics,Cameras,2.0,89.89,110.0,152.81,130.19,22.62,Debit Card,Returned,Standard,6.0,Yes,Mia Taylor,4.0,111,2024

In [65]:
df.drop(16177,inplace=True)

In [66]:
px.box(data_frame= df, x= 'Discount_Percentage', title= 'Discount_Percentage')

#### Feature Engineering

##### ADD Month Name Column

In [67]:
import datetime as dt

In [68]:
df['month_name'] = df['Order_Date'].dt.month_name()

In [69]:
df

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year,month_name
0,C01482,Sophia Smith,28,Male,Consumer,2022-10-06,Online,Los Angeles Downtown,United States,West,Los Angeles,Webcam HD,Electronics,Cameras,2.0,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81,2022,October
1,C01591,Hannah King,46,Female,Consumer,2024-06-03,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6.0,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123,2024,June
2,C04140,Emma Wilson,42,Male,Consumer,2024-12-19,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2.0,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93,2024,December
3,C03663,Daniel Clark,18,Male,Corporate,2025-10-05,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11.0,115.34,15.0,1078.46,897.91,180.55,PayPal,Completed,Next Day,2.0,No,Grace Harris,4.0,59,2025,October
4,C02749,Sophia Smith,37,Male,Returning Customer,2022-09-13,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4.0,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56,2022,September
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16886,C03487,Ella Adams,32,Male,New Customer,2022-01-11,Online,Sydney CBD,Australia,New South Wales,Sydney,Portable Heater,Appliances,Climate,1.0,93.25,0.0,93.25,66.55,26.70,Credit Card,Completed,Express,2.0,No,Emma Carter,5.0,52,2022,January
16887,C00418,Jack Jones,32,Male,Returning Customer,2023-10-09,Retail Store,London City,United Kingdom,England,London,AeroBook 14 Laptop,Electronics,Laptops,2.0,901.65,5.0,1713.14,1401.99,311.15,Credit Card,Processing,Standard,3.0,No,Emma Carter,4.0,107,2023,October
16888,C03311,Oscar Williams,37,Male,Corporate,2025-04-02,Online,London City,United Kingdom,England,London,Security Camera,Electronics,Cameras,1.0,159.93,10.0,143.93,116.02,27.91,Apple Pay,Completed,Standard,6.0,No,Sophia Brown,2.0,58,2025,April
16889,C01590,Benjamin Moore,21,Female,New Customer,2022-06-08,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Notebook Pack,Office Supplies,Paper,2.0,27.20,0.0,54.41,32.71,21.70,Debit Card,Completed,Standard,7.0,No,Noah Wilson,3.0,32,2022,June
16890,C01479,Lucas Allen,55,Male,Consumer,2025-06-30,Retail Store,Toronto Central,Canada,Ontario,Toronto,Backup Drive 2TB,Electronics,Storage,1.0,139.31,0.0,139.31,102.21,37.10,PayPal,Completed,Pickup,0.0,No,Grace Harris,5.0,73,2025,June

In [70]:
df.reset_index(drop=True)

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year,month_name
0,C01482,Sophia Smith,28,Male,Consumer,2022-10-06,Online,Los Angeles Downtown,United States,West,Los Angeles,Webcam HD,Electronics,Cameras,2.0,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81,2022,October
1,C01591,Hannah King,46,Female,Consumer,2024-06-03,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6.0,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123,2024,June
2,C04140,Emma Wilson,42,Male,Consumer,2024-12-19,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2.0,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93,2024,December
3,C03663,Daniel Clark,18,Male,Corporate,2025-10-05,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11.0,115.34,15.0,1078.46,897.91,180.55,PayPal,Completed,Next Day,2.0,No,Grace Harris,4.0,59,2025,October
4,C02749,Sophia Smith,37,Male,Returning Customer,2022-09-13,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4.0,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56,2022,September
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16885,C03487,Ella Adams,32,Male,New Customer,2022-01-11,Online,Sydney CBD,Australia,New South Wales,Sydney,Portable Heater,Appliances,Climate,1.0,93.25,0.0,93.25,66.55,26.70,Credit Card,Completed,Express,2.0,No,Emma Carter,5.0,52,2022,January
16886,C00418,Jack Jones,32,Male,Returning Customer,2023-10-09,Retail Store,London City,United Kingdom,England,London,AeroBook 14 Laptop,Electronics,Laptops,2.0,901.65,5.0,1713.14,1401.99,311.15,Credit Card,Processing,Standard,3.0,No,Emma Carter,4.0,107,2023,October
16887,C03311,Oscar Williams,37,Male,Corporate,2025-04-02,Online,London City,United Kingdom,England,London,Security Camera,Electronics,Cameras,1.0,159.93,10.0,143.93,116.02,27.91,Apple Pay,Completed,Standard,6.0,No,Sophia Brown,2.0,58,2025,April
16888,C01590,Benjamin Moore,21,Female,New Customer,2022-06-08,Online,Cologne Business,Germany,North Rhine-Westphalia,Cologne,Notebook Pack,Office Supplies,Paper,2.0,27.20,0.0,54.41,32.71,21.70,Debit Card,Completed,Standard,7.0,No,Noah Wilson,3.0,32,2022,June
16889,C01479,Lucas Allen,55,Male,Consumer,2025-06-30,Retail Store,Toronto Central,Canada,Ontario,Toronto,Backup Drive 2TB,Electronics,Storage,1.0,139.31,0.0,139.31,102.21,37.10,PayPal,Completed,Pickup,0.0,No,Grace Harris,5.0,73,2025,June

In [71]:
df.to_parquet('cleaned_data.parquet',index= False)
df.to_csv('cleaned_data.csv',index= False)

#### Data Analysis

####
- How do sales change over time?
- Which products and categories perform best?
- Which city generate the most revenue?
- How do discounts affect profit?
- Which sales channels perform best?
- What are the most profitable products?
- Are there seasonal sales patterns?

In [72]:
import streamlit as st

In [73]:
df.head()

,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_Name,Country,Region,City,Product_Name,Product_Category,Product_Subcategory,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Sales_Representative,Customer_Rating,Inventory_Level,Order_Year,month_name
0,C01482,Sophia Smith,28,Male,Consumer,2022-10-06,Online,Los Angeles Downtown,United States,West,Los Angeles,Webcam HD,Electronics,Cameras,2.0,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed,Standard,4.0,No,James Anderson,4.0,81,2022,October
1,C01591,Hannah King,46,Female,Consumer,2024-06-03,Online,Sydney CBD,Australia,New South Wales,Sydney,Office Keyboard,Electronics,Accessories,6.0,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed,Standard,6.0,No,Ella Lewis,5.0,123,2024,June
2,C04140,Emma Wilson,42,Male,Consumer,2024-12-19,Online,Paris Central,France,Île-de-France,Paris,Copy Paper Box,Office Supplies,Paper,2.0,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped,Standard,4.0,No,Liam Davis,4.0,93,2024,December
3,C03663,Daniel Clark,18,Male,Corporate,2025-10-05,B2B Portal,New York Central,United States,Northeast,New York,SmartDock USB-C,Electronics,Accessories,11.0,115.34,15.0,1078.46,897.91,180.55,PayPal,Completed,Next Day,2.0,No,Grace Harris,4.0,59,2025,October
4,C02749,Sophia Smith,37,Male,Returning Customer,2022-09-13,B2B Portal,Chicago Loop,United States,Midwest,Chicago,Desk Lamp,Furniture,Lighting,4.0,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed,Express,2.0,No,Sophia Brown,2.0,56,2022,September

#### KPI

In [74]:
df['Customer_Name'].nunique()

1177

In [75]:
df['Country'].nunique()

6

In [76]:
df['Product_Category'].nunique()

4

In [77]:
df['Profit'].sum()

np.float64(1548553.31)

In [78]:
df['Unit_Price'].mean().round(2)

np.float64(233.32)

In [103]:
df['Customer_Rating'].mean().round(2)

np.float64(3.99)

In [104]:
df['Delivery_Days'].mean().round(2)

np.float64(2.26)

In [80]:
px.pie(data_frame= df, names= 'Product_Category', hole= 0.5 , title= 'Products Type')

In [81]:
Best_Selling_Country = df.groupby('Country')['Sales_Amount'].sum().reset_index().sort_values(by='Sales_Amount',ascending=False).reset_index(drop=True)
Best_Selling_Country

          Country  Sales_Amount
0   United States    3333988.61
1  United Kingdom    1229955.92
2          Canada    1128768.09
3         Germany     904573.14
4          France     671657.23
5       Australia     479367.86

In [82]:
Best_Selling_Country.iloc[0]

Country         United States
Sales_Amount       3333988.61
Name: 0, dtype: object

In [83]:
Best_Selling_City = df.groupby('City')['Sales_Amount'].sum().reset_index().sort_values(by='Sales_Amount',ascending=False).reset_index(drop=True)
Best_Selling_City

           City  Sales_Amount
0   Los Angeles     954959.95
1      New York     951606.84
2        London     797600.60
3       Chicago     719566.80
4        Austin     707855.02
5         Paris     671657.23
6       Toronto     646825.72
7        Munich     549138.80
8     Vancouver     481942.37
9        Sydney     479367.86
10   Manchester     432355.32
11      Cologne     355434.34

In [84]:
px.bar(data_frame= Best_Selling_City, y= 'City', x= 'Sales_Amount', text_auto= True,
       labels= {'Sales_Amount' : 'Total Sales'},
       title= 'Sales Per City')

In [85]:
Best_Selling_City.iloc[0]

City            Los Angeles
Sales_Amount      954959.95
Name: 0, dtype: object

#### Best Representative

In [86]:
df_Representative= df.groupby('Sales_Representative')['Sales_Amount'].sum().reset_index().sort_values(by='Sales_Amount',ascending=False).reset_index(drop=True).head(3)
df_Representative.head(3)

  Sales_Representative  Sales_Amount
0        Michael Clark     542711.37
1          Lucas Moore     542201.00
2           Mia Taylor     506210.82

In [87]:
px.bar(data_frame= df_Representative, y= 'Sales_Amount', x= 'Sales_Representative', text_auto= True,
       labels= {'Sales_Amount' : 'Total Sales'},
       title= 'Top Performers')

#### Sales Insights

In [88]:
df_year=df.groupby('Order_Year')['Sales_Amount'].sum().reset_index()
df_year

   Order_Year  Sales_Amount
0        2022    1902496.56
1        2023    1895424.87
2        2024    1806009.12
3        2025    2144380.30

In [89]:
px.line(data_frame= df_year, x= 'Order_Year', y= 'Sales_Amount')

#### Profit / Year

In [90]:
df_Profit = df.groupby('Order_Year')['Profit'].sum().reset_index()
df_Profit

   Order_Year     Profit
0        2022  385938.59
1        2023  376480.20
2        2024  362513.52
3        2025  423621.00

In [91]:
px.line(data_frame= df_Profit, x= 'Order_Year', y= 'Profit')

### Most Selling Category in each year

In [92]:
df_category=df.groupby(['Product_Category','Order_Year'])['Sales_Amount'].sum().reset_index()
df_category

   Product_Category  Order_Year  Sales_Amount
0        Appliances        2022     152612.87
1        Appliances        2023     137367.60
2        Appliances        2024     116754.70
3        Appliances        2025     141216.31
4       Electronics        2022    1084046.87
5       Electronics        2023    1119533.38
6       Electronics        2024    1103146.65
7       Electronics        2025    1343478.47
8         Furniture        2022     490535.27
9         Furniture        2023     455383.57
10        Furniture        2024     435049.61
11        Furniture        2025     475589.41
12  Office Supplies        2022     175301.55
13  Office Supplies        2023     183140.32
14  Office Supplies        2024     151058.16
15  Office Supplies        2025     184096.11

In [93]:
most_selling_category =df_category.loc[df_category.groupby('Order_Year')['Sales_Amount'].idxmax()].reset_index(drop=True)
most_selling_category

  Product_Category  Order_Year  Sales_Amount
0      Electronics        2022    1084046.87
1      Electronics        2023    1119533.38
2      Electronics        2024    1103146.65
3      Electronics        2025    1343478.47

In [110]:
px.bar(data_frame= most_selling_category, y= 'Sales_Amount', x= 'Order_Year', text_auto= True,color='Product_Category',
       labels= {'Sales_Amount' : 'Total Sales'},
       title= 'Top Product Category each year')

### Best Selling Sales Channel

In [95]:
df_Sales_Channel = df.groupby('Sales_Channel')['Sales_Amount'].sum().reset_index().sort_values(by='Sales_Amount',ascending=False).reset_index(drop=True)
df_Sales_Channel

  Sales_Channel  Sales_Amount
0        Online    2938097.91
1  Retail Store    2309032.47
2    B2B Portal    1987856.38
3   Phone Order     513324.09

In [96]:
px.bar(data_frame= df_Sales_Channel, y= 'Sales_Amount', x= 'Sales_Channel', text_auto= True,
       labels= {'Sales_Amount' : 'Total Sales'},
       title= 'Sales Per Channel')

How do discounts affect profit?

In [97]:
df_percentage_Profit=df[['Discount_Percentage','Profit']]
df_percentage_Profit
corr_df = df_percentage_Profit.corr(numeric_only= True).round(2)
corr_df

                     Discount_Percentage  Profit
Discount_Percentage                 1.00   -0.19
Profit                             -0.19    1.00

In [98]:
px.imshow(corr_df, text_auto= True)

In [99]:
df['Discount_Percentage'].corr(df['Profit'])

np.float64(-0.19386724446148312)

In [100]:
px.scatter(df, x= 'Discount_Percentage', y= 'Profit', trendline= 'ols', trendline_color_override= 'red',
           title= 'Discount_Percentage vs Profit' )

Are there seasonal sales patterns?

In [101]:
df_month=df.groupby('month_name')['Sales_Amount'].sum().reset_index().sort_values(by='Sales_Amount',ascending=False).reset_index(drop=True) 
df_month

   month_name  Sales_Amount
0    December     885384.06
1    November     843701.74
2     October     765785.08
3         May     668934.19
4       March     668243.36
5       April     626190.13
6      August     608146.10
7   September     586130.42
8        July     577658.14
9        June     554819.66
10   February     483251.63
11    January     480066.34

#### IT seems that Winter is the season of Best sales Numbers

What are the most profitable products?

In [102]:
df_Profit_Product = df.groupby('Product_Name')['Profit'].sum().reset_index().sort_values(by='Profit',ascending=False).reset_index(drop=True)
df_Profit_Product.head(10)
px.bar(data_frame= df_Profit_Product.head(10), y= 'Profit', x= 'Product_Name', text_auto= True,
       labels= {'Profit' : 'Total Profit'}, title= 'Top 10 Most Profitable Products')